CREATE TABLE USERS(
	USER_ID VARCHAR2(20) PRIMARY KEY,
	PWD VARCHAR2(20) NOT NULL,
	NAME VARCHAR2(20) NOT NULL,
	BIRTH VARCHAR2(10) NOT NULL,
	USER_STATUS VARCHAR2(15) DEFAULT 'USER' CHECK(USER_STATUS IN ('USER','ADMIN'))
);

CREATE TABLE CATEGORY(
	CATEGORY_ID VARCHAR2(10) PRIMARY KEY,
	CATEGORY_KIND VARCHAR2(15) NOT NULL CHECK(CATEGORY_KIND IN ('ENJOY','STUDY'))
);

CREATE SEQUENCE SEQ_MOIM 
MINVALUE 1 START WITH 1 INCREMENT BY 1;

CREATE TABLE MOIM(
	MOIM_ID VARCHAR2(20) PRIMARY KEY,
	MOIM_IMG VARCHAR2(255),
	TITLE VARCHAR2(30) NOT NULL,
	SDATE DATE NOT NULL,
	EDATE DATE NOT NULL,
	REG_DATE DATE DEFAULT SYSDATE,
	APPLY_SDATE DATE NOT NULL,
	APPLY_EDATE DATE NOT NULL,
	PLACE VARCHAR2(100) NOT NULL,
	CATEGORY_ID VARCHAR2(10) NOT NULL REFERENCES CATEGORY (CATEGORY_ID),
	USER_ID VARCHAR2(20) NOT NULL REFERENCES USERS (USER_ID)
);

CREATE TABLE USER_MOIM(
	USER_ID VARCHAR2(20) NOT NULL REFERENCES USERS(USER_ID),
	MOIM_ID VARCHAR2(50) NOT NULL REFERENCES MOIM(MOIM_ID),
	PRIMARY KEY(USER_ID,MOIM_ID)
);

CREATE TABLE DETAIL(
	DETAIL_ID VARCHAR2(50) PRIMARY KEY,
	MOIM_ID VARCHAR2(50) NOT NULL REFERENCES MOIM(MOIM_ID),
	CONTENT VARCHAR2(4000),
	DETAIL_IMG1 VARCHAR2(255),
	DETAIL_IMG2 VARCHAR2(255),
	DETAIL_IMG3 VARCHAR2(255),
	DETAIL_IMG4 VARCHAR2(255),
	DETAIL_IMG5 VARCHAR2(255)
);

INSERT INTO CATEGORY VALUES ('c1','ENJOY');
INSERT INTO CATEGORY VALUES ('c2','STUDY');

ALTER TABLE MOIM MODIFY SDATE VARCHAR2(30);
ALTER TABLE MOIM MODIFY EDATE VARCHAR2(30);
ALTER TABLE MOIM MODIFY APPLY_SDATE VARCHAR2(30);
ALTER TABLE MOIM MODIFY APPLY_EDATE VARCHAR2(30);
ALTER TABLE MOIM ADD STIME VARCHAR(7);
ALTER TABLE MOIM ADD ETIME VARCHAR(7);
ALTER TABLE MOIM ADD APPLY_STIME VARCHAR(7);
ALTER TABLE MOIM ADD APPLY_ETIME VARCHAR(7);
ALTER TABLE MOIM MODIFY STIME VARCHAR(7) NOT NULL;
ALTER TABLE MOIM MODIFY ETIME VARCHAR(7) NOT NULL;
ALTER TABLE MOIM MODIFY APPLY_STIME VARCHAR(7) NOT NULL;
ALTER TABLE MOIM MODIFY APPLY_ETIME VARCHAR(7) NOT NULL;

INSERT INTO USERS VALUES ('u2','1q2w','EILEEN','19921208','user');

ALTER TABLE MOIM MODIFY TITLE VARCHAR(255) NOT NULL;

CREATE SEQUENCE SEQ_DETAIL 
MINVALUE 1 START WITH 1 INCREMENT BY 1;

DROP TABLE DETAIL;

ALTER TABLE MOIM ADD CONTENT VARCHAR2(4000);
ALTER TABLE MOIM ADD DETAIL_IMG1 VARCHAR2(255);
ALTER TABLE MOIM ADD DETAIL_IMG2 VARCHAR2(255);
ALTER TABLE MOIM ADD DETAIL_IMG3 VARCHAR2(255);
ALTER TABLE MOIM ADD DETAIL_IMG4 VARCHAR2(255);
ALTER TABLE MOIM ADD DETAIL_IMG5 VARCHAR2(255);

DROP TABLE DETAIL;

CREATE TABLE DETAIL(
	DETAIL_ID VARCHAR2(50) PRIMARY KEY,
	MOIM_ID VARCHAR2(50) NOT NULL REFERENCES MOIM(MOIM_ID)
);

INSERT INTO USERS VALUES ('u10','1q2w','EILEEN','19921208','USER');
INSERT INTO USERS VALUES ('admin','admin','EILEEN','19921208','ADMIN');

UPDATE MOIM SET PLACE = '서울특별시 강남구 역삼동 테헤란로 212';